#!/bin/bash

#Publish
mkdir -p /tmp/exports
mkdir -p /tmp/topublish
if [ $GIT = 'true' ];then
    GITURL="$(echo $GITURL | sed 's|https://||g')"
    git config --global user.email "srherobrine20@gmail.com"
    git config --global user.name "Sirherobrine23"

    echo "Atuamente só suportamos links com https://. , o git:// não esta funcionanod por enquanto"
    echo "estamos clonando com as seguintes informações: https://$GITUSER:*****@$GITURL ,Branch: $GITBRANCH"
    git clone https://$GITUSER:$GITPASS@$GITURL -b $GITBRANCH /tmp/exports/publish/
else
 echo 'Não foi informado um metodo para subir o arquivo !!!'
 exit 23
fi



#----------------------------------------------------------------------------------------------------------------------------------------------------
for asss in packages/*
do  
    echo
    echo
    echo
    echo
    mkdir -p /tmp/$asss-build/
    cp -rf $asss/. /tmp/$asss-build/
    # removendo arquivos do diretorio para a pasta /tmp/deb-copiler
    rm -rf /tmp/$asss-build/.git*
    rm -rf /tmp/$asss-build/LICE*
    rm -rf /tmp/$asss-build/README*
    rm -rf /tmp/$asss-build/*.md

    # Pre script - build

    if [ $SCRIPT = 'true' ]
    then
        export DORRS=$(echo "$asss")
        export PRESCRIPT
        script-sh23
    fi

    #----------------------------------------------------------------------------------------------------------------------------------------------------
    # Nome do Pacotes

    [ -d /tmp/$asss-build/DEBIAN ] && DEBIAN_DIR=DEBIAN
    [ -d /tmp/$asss-build/debian ] && DEBIAN_DIR=debian

    echo "Diretorio do arquivos do Debian Package: /tmp/$asss-build/$DEBIAN_DIR "

    NAME="$(cat /tmp/$asss-build/$DEBIAN_DIR/control | grep 'Package:' | sed 's|Package: ||g' | sed 's|Package:||g')"
    VERSION="$(cat /tmp/$asss-build/$DEBIAN_DIR/control | grep 'Version: ' | grep -v 'Standards-Version' | sed 's|Version: ||g')"
    ARQUITETURA="$(cat /tmp/$asss-build/$DEBIAN_DIR/control | grep 'Architecture: ' | sed 's|Architecture: ||g')"

    # postinst
    if [ -e /tmp/$asss-build/$DEBIAN_DIR/postinst ]
    then
    chmod 775 /tmp/$asss-build/$DEBIAN_DIR/postinst
    fi
    # preinst
    if [ -e /tmp/$asss-build/$DEBIAN_DIR/preinst ]
    then 
    chmod 775 /tmp/$asss-build/$DEBIAN_DIR/postinst
    fi
    # prerme
    if [ -e /tmp/$asss-build/$DEBIAN_DIR/prerme ]
    then
    chmod 775 /tmp/$asss-build/$DEBIAN_DIR/prerme
    fi
    # postrm
    if [ -e /tmp/$asss-build/$DEBIAN_DIR/postrm ]
    then
    chmod 755 /tmp/$asss-build/$DEBIAN_DIR/postrm
    fi

    # Execute in all bin foldes 
    for abin in $(find /tmp/$asss-build/ -name '*bin')
    do
    chmod a+x ${abin}/*
    chmod 775 ${abin}/*
    done

    #----------------------------------------------------------------------------------------------------------------------------------------------------
    # Informações do pacote
    echo "Nome do Pacote:                        - $NAME "
    echo "Versão do Pacote:                      - $VERSION "
    echo "Arquitetura do processador suportados: - $ARQUITETURA "

    DEB_OUTPUT="$(echo "$NAME $VERSION $ARQUITETURA" | sed 's| |_|g').deb"

    #----------------------------------------------------------------------------------------------------------------------------------------------------
    # Copilando o arquivo
    echo "vamos criar um pacote com as seguintes configurações: $DEB_OUTPUT"
    dpkg-deb --build /tmp/$asss-build/. /tmp/topublish/$DEB_OUTPUT && success=0 || exit 23
    echo "Done"

    
done
#----------------------------------------------------------------------------------------------------------------------------------------------------
#Publish
if [ $FTP = 'true' ];then
    curl -T /tmp/$DEB_OUTPUT ftp://$FTPURL/$FTPDIR/ --user $USERSMB:$PASSSMB || ftp-upload --debug --passive -h $FTPURL -u "$USERSMB" --password "$PASSSMB" -d "$FTPDIR" "$DEB_OUTPUT.deb"
elif [ $GIT = 'true' ];then
    cd /tmp/exports/publish/
    cp -f /tmp/topublish/*.deb /tmp/exports/publish/$GITDIR/
    git add .
    git commit -m "$NAME - Upload by Debian_docker By sh23"
    git push
else
 echo 'Não foi informado um metodo para subir o arquivo !!!'
 exit 23
fi
